#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='\033[1;36m\u@\h:\033[0m\W\033[1;36m|$\033[0m '

export BUILDDIR=/tmp/makepkg
export HISTSIZE=10000
export HISTFILESIZE=100000
